name: my_porfolio
description: porfolio web app

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences:


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get: ^4.5.1
  responsive_builder:
  scrollable_positioned_list: ^0.3.5
  url_launcher: ^6.0.2
  carousel_slider: ^4.2.1
  animated_text_kit: ^4.2.2
  mailto: ^2.0.0
  email_validator: ^2.0.1
  path_provider: ^2.0.14
  image_picker: ^0.8.7+4
  flutter_email_sender: ^5.2.0
  flutter_animation_progress_bar: ^2.3.1
  pie_chart: ^5.3.2
  fluttertoast:
  pinch_zoom_release_unzoom:
  flutter_launcher_icons: ^0.13.1
  shadow: ^1.5.0
  flashy_tab_bar2: ^0.0.5
  auto_size_text: ^3.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo/black_transparent.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/logo/black_transparent.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/logo/black_transparent.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/logo/black_transparent.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/logo/
    - assets/images/icons/
    - assets/images/projects/
    - assets/audios/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
  
    - family: AlfaSlabOne
      fonts:
        - asset: assets/fonts/AlfaSlabOne-Regular.ttf

    - family: AmaticSC
      fonts:
        - asset: assets/fonts/AmaticSC-Regular.ttf
        - asset: assets/fonts/AmaticSC-Bold.ttf
          weight: 700
          
    - family: BalsamiqSans
      fonts:
        - asset: assets/fonts/BalsamiqSans-Regular.ttf
        - asset: assets/fonts/BalsamiqSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/BalsamiqSans-Italic.ttf
          style: italic
          
    - family: Caveat
      fonts:
        - asset: assets/fonts/Caveat-Regular.ttf
        - asset: assets/fonts/Caveat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Caveat-Medium.ttf
          weight: 300
        - asset: assets/fonts/Caveat-SemiBold.ttf
          weight: 600

    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-Regular.ttf
        - asset: assets/fonts/Comfortaa-Bold.ttf
          weight: 700
        - asset: assets/fonts/Comfortaa-Light.ttf
          weight: 200
        - asset: assets/fonts/Comfortaa-Medium.ttf
          weight: 300
        - asset: assets/fonts/Comfortaa-SemiBold.ttf
          weight: 600
          
    - family: Cookie
      fonts:
        - asset: assets/fonts/Cookie-Regular.ttf
        
    - family: GloriaHallelujah
      fonts:
        - asset: assets/fonts/GloriaHallelujah-Regular.ttf

    - family: IndieFlower
      fonts:
        - asset: assets/fonts/IndieFlower-Regular.ttf

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Light.ttf
          weight: 200
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 300
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 100

    - family: MeowScript
      fonts:
        - asset: assets/fonts/MeowScript-Regular.ttf

    - family: MontserratAlternates
      fonts:
        - asset: assets/fonts/MontserratAlternates-Regular.ttf
        - asset: assets/fonts/MontserratAlternates-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/MontserratAlternates-Bold.ttf
          weight: 700
        - asset: assets/fonts/MontserratAlternates-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/MontserratAlternates-Italic.ttf
          style: italic
        - asset: assets/fonts/MontserratAlternates-Light.ttf
          weight: 200
        - asset: assets/fonts/MontserratAlternates-Medium.ttf
          weight: 300
        - asset: assets/fonts/MontserratAlternates-ExtraLight.ttf
          weight: 100

    - family: Mulish
      fonts:
        - asset: assets/fonts/Mulish-Regular.ttf
        - asset: assets/fonts/Mulish-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Mulish-Bold.ttf
          weight: 700
        - asset: assets/fonts/Mulish-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Mulish-Italic.ttf
          style: italic
        - asset: assets/fonts/Mulish-Light.ttf
          weight: 200
        - asset: assets/fonts/Mulish-Medium.ttf
          weight: 300
        - asset: assets/fonts/Mulish-ExtraLight.ttf
          weight: 100

    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 300

    - family: ReadexPro
      fonts:
        - asset: assets/fonts/ReadexPro-Regular.ttf
        - asset: assets/fonts/ReadexPro-Bold.ttf
          weight: 700
        - asset: assets/fonts/ReadexPro-Light.ttf
          weight: 200
        - asset: assets/fonts/ReadexPro-Medium.ttf
          weight: 300
        - asset: assets/fonts/ReadexPro-ExtraLight.ttf
          weight: 100

    - family: RedactedScript
      fonts:
        - asset: assets/fonts/RedactedScript-Regular.ttf
        - asset: assets/fonts/RedactedScript-Bold.ttf
          weight: 700
        - asset: assets/fonts/RedactedScript-Light.ttf
          weight: 200
          
    - family: Righteous
      fonts:
        - asset: assets/fonts/Righteous-Regular.ttf
        
    - family: Shalimar
      fonts:
        - asset: assets/fonts/Shalimar-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
